### GET Request
POST http://localhost:5000/farmerId
Content-Type: application/json

{
    "farmerId" : 153227
}

### Post request
POST http://localhost:5000/init
Content-Type: application/json


### POST
POST http://localhost:5000/temp_no
Content-Type: application/json

{
    "test_cd" : 1
}

### Cluster CODE
POST http://localhost:5000/clusterInfo
Content-Type: application/json

{
    "farmerId" : 153227
}

### Village CODE
POST http://localhost:5000/villageInfo
Content-Type: application/json

{
    "farmerId" : 153227,
    "clusterCd" : 3
}

### Survey No

POST http://localhost:5000/surveyno
Content-Type: application/json

{
    "farmerId" : 153227,
    "clusterCd" : 3,
    "villageCd" : 27
    
}
### PLOT Info
POST http://localhost:5000/plotNo
Content-Type: application/json

{
    "farmerId" : 153227,
    "villageCd" : 27
}
### Plot Area
POST http://localhost:5000/plotArea
Content-Type: application/json

{
    "farmerId" : 153227,
    "villageCd" : 27,
    "plotNo": 2
}
### Parameter info 

### Suggestion 
POST http://localhost:5000/suggestions
Content-Type: application/json

{
    "test" : "1"
}
### New suggestion
POST http://localhost:5000/newSuggestion
Content-Type: application/json

{   
    "newSuggestion" : "TEMP",
    "test" : "1"
}
### Values

POST http://localhost:5000/values
Content-Type: application/json

{
    "values" : {
  "farmerId": "153227",
  "labNo": [{ "LAB_TRAN": 12369 }],
  "test": "1",
  "surveyNo": "B 193/1",
  "cluster": "3",
  "village": "27",
  "plotNo": 2,
  "drainage": "GOOD",
  "soilType": "2",
  "waterType": "",
  "irrigationSource": "3",
  "cultivationType": "RAINED",
  "previousCrop": "SUNFLOWER",
  "cropToBeGrown": "SUNFLOWER",
  "dtOfSampling": "2024-03-19",
  "dtOfSamplingReceipt": "2024-03-19",
  "templateNo": [{ "TEMPLATE_NO": 2 }],
  "HEWFno": "",
  "area": 5
},
    "paramValues" : {
  "11": "2",
  "12": "3",
  "14": "3",
  "15": "3",
  "16": "3",
  "17": "3",
  "19": "3",
  "20": "3",
  "21": "3",
  "23": "3",
  "24": "3",
  "25": "4",
  "26": "33",
  "27": "3",
  
},
    "suggestions" : [
        
    ]
}
### Parameters
POST http://localhost:5000/parameters
Content-Type: application/json

{
    "test" : "1"
}
### Get values
GET http://localhost:5000/getValues

###Yield Target
POST http://localhost:5000/yield_target
Content-Type: application/json

### Codes
POST http://localhost:5000/combination_cds
Content-Type: application/json

###b NPK
POST http://localhost:5000/npk
Content-Type: application/json
### Lab tran edit
POST http://localhost:5000/checkLabTran
Content-Type: application/json

{   
   "labNo": 12407
}
### Season 
POST http://localhost:5000/season
Content-Type: application/json

{}
### Transactions
POST http://localhost:5000/transactions
Content-Type: application/json

{
    "startDate" : "2024-04-09",
    "endDate" : "2024-04-25"
}
### Test 
POST http://localhost:5000/test
Content-Type: application/json

{   
   "labTran": 12579
}
### Login 
POST http://localhost:5000/login
Content-Type: application/json

{   
   "username": "Kshitij",
    "password": "123456"
}

### Sign Up
POST http://localhost:5000/signUp
Content-Type: application/json

{   
   "username": "Kshitij",
    "password": "123456"
}
### Calc

POST http://localhost:5000/calc
Content-Type: application/json

{   
    "parameters" : {
        "nitr" : 10,
        "phos" : 8,
        "pota" : 9
    }
    
}