### GET Request
POST http://localhost:5000/farmerId
Content-Type: application/json

{
    "farmerId" : 153227
}

### Post request
POST http://localhost:5000/init
Content-Type: application/json


### POST
POST http://localhost:5000/temp_no
Content-Type: application/json

{
    "test_cd" : 1
}

### Cluster CODE
POST http://localhost:5000/clusterInfo
Content-Type: application/json

{
    "farmerId" : 153227
}

### Village CODE
POST http://localhost:5000/villageInfo
Content-Type: application/json

{
    "farmerId" : 153227,
    "clusterCd" : 3
}

### PLOT Info
POST http://localhost:5000/plotNo
Content-Type: application/json

{
    "farmerId" : 153227,
    "villageCd" : 27
}